export interface ChallengeProps {
    title: string;
    value: string | number;
    description: string;
    claimed?: boolean;
};

export interface StatsProps {
    earned: number;
    longestFish: number;
    fishCaught: number;
};

export interface LeaderboardProps {
    name: string;
    longestFish: number;
    earned: number;
    fishCaught: number;
    me?: boolean;
    id?: number; // Generated by function!!
};

export interface Base {
    nickname: string;
    challenges: ChallengeProps[];
};