export interface ChallengeProps {
    title: string;
    value: string | number;
    description: string;
    claimed?: boolean;
};

export interface StatsProps {
    earned: number;
    longestFish: number;
    fishCaught: number;
};

export interface LeaderboardProps {
    name: string;
    longestFish: number;
    earned: number;
    fishCaught: number;
    me?: boolean;
    id?: number; // Generated by function!!
};

export interface Base {
    nickname: string;
    challenges: ChallengeProps[];
};

export interface ShopProps {
    name: string;
    label: string;
    imageUrl: string;
    price: number;
    rarity?: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
};

export interface SellProps {
    label: string;
    imageUrl: string;
    rarity?: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
    price: number;
    length: number;
};

export interface TabletProps {
    leaderboard: LeaderboardProps[];
    statistics: StatsProps;
    shop: ShopProps[];
    sell: SellProps[];
};

export interface CartProps {
    name: string;
    count: number
}